### PR TITLE
Translated German sentence

### PR DESCRIPTION
**Pull request by JeroenOortwijn**
Translated the German sentence in the English section with Google Translate.

### CODE REVIEW

**Comment by GruberMarkus** [comment]
Thank you very much!

The sentence will be translated in v4.6.1, which will be published later today.

**Comment by JeroenOortwijn** [comment]
If found another line:
`### 1.6.1. Allgemeine Beschreibung, Lizenzmodell`

**Comment by GruberMarkus** [comment]
Thank you! This will be taken care of in the release after v4. 6.1.

**Comment by GruberMarkus** [comment]
Fixed in v4.7.0.

**Pull request closed without merging**
